### ISSUE TITLE
Specify secrets without project identifier

### ISSUE THREAD

**Issue by rvdh** [google-github-actions/get-secretmanager-secrets#163]
### TL;DR

Is it possible to introduce an even shorter version of specifying the secret? Without the project identifier? The first step in using this action is [authenticating using google-github-actions/auth](https://github.com/google-github-actions/get-secretmanager-secrets#via-google-github-actionsauth) - I figured it should be possible to derive the project identifier from that step?

This would help us in making generic workflow files that we can use in different GCP projects, without having to change all the project identifiers.

**Comment by sethvargo** [comment]
Hi @rvdh 

Thank you for the PR. I'm against adding this as a first-class feature, because sometimes project resolution may produce an unexpected result, and I wouldn't want someone accidentally reading the wrong secret. It's also incredibly difficult to debug.

If you're looking to make a "portable" action that works regardless of the project, you could store the project ID in an `env` block in the action.yml and then reference it as-needed.


```yaml
env:
  PROJECT_ID: my-project

jobs:
  my_job:
    steps:
    - uses: google-github-actions/auth@v0
      with:
        project_id: '${{ env.PROJECT_ID }}'

    - uses: google-github-actions/get-secretmanager-secrets@v0
      with:
        secrets: |-
          my-output:${{ env.PROJECT_ID }}/my-secret
```
