### ISSUE TITLE
Support secrets containing json

### ISSUE THREAD

**Issue by rvdh** [google-github-actions/get-secretmanager-secrets#165]
### TL;DR

It would be nice if we could get specific keys from json secrets directly into an output variable.

### Detailed design

```markdown
- id: 'secrets'
  uses: 'google-github-actions/get-secretmanager-secrets@v0'
  with:
    secrets: |-
      token:my-project/docker-registry:token
      username:my-project/docker-registry:username
```

We're in the process of moving our secrets from Hashicorp Vault to Google Secret Manager. In Vault, we store the secrets as json. If we simply copy over the data to Google Secret Manager, we get our json in the output variable we specify in the plugin, which then needs further processing to get to a specific key.

It would be nice if we could specify the exact key we're interested in in the `secrets` input.

**Comment by sethvargo** [comment]
Hi @rvdh 

There's a long-standing feature request to make this a first-class citizen in the Secret Manager API. In the meantime, I think the best option is to use [`fromJSON`](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson):

```yaml
- id: 'secrets'
  uses: 'google-github-actions/get-secretmanager-secrets@v0'
  with:
    secrets: |-
      token:my-project/docker-registry
      username:my-project/docker-registry

- name: 'do something with secrets'
  run: |-
    echo "${{ fromJSON(steps.secrets.outputs.token).token }}"
```
