### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter ''using: node16' is not supported

### ISSUE THREAD

**Issue by marco-scoppetta-qatalog** [google-github-actions/get-secretmanager-secrets#193]
### TL;DR

Hi all,

after the recent change (https://github.com/google-github-actions/get-secretmanager-secrets/commit/3496e55a9a37020bcc47d439003e33f420d2d0e7) to switch to Node16 by default,
we are getting:

```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. 
(Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
   
Error: Fail to load google-github-actions/get-secretmanager-secrets/main/action.yml
```

in our CI pipeline. 

Anyone else having this issue?
Any way we can fix it on our side?

Thank you!

### Action YAML

```yaml
name: Docker build check
on: [workflow_dispatch, pull_request]
concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker-build:
    runs-on: [self-hosted, preemptible]
    env:
      NODE_ENV: test
    steps:
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.xxx }}
          service_account_key: ${{ secrets.xxx }}
          export_default_credentials: true
          credentials_file_path: .xxx.json
      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            CMS_API_TOKEN:xxx/INTEGRATION_XXX
            SHEETS_CMS_API_KEY:xxx/SHEETS_XXX
      - name: write .env
        run: |
          cat << EOF > .env
          BUTTERCMS_API_TOKEN=${{ steps.secrets.outputs.BUTTERCMS_API_TOKEN }}
          GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          SHEETS_TO_CMS_API_KEY=${{ steps.secrets.outputs.SHEETS_TO_CMS_API_KEY }}
          EOF
      - name: docker login
        run: |-
          gcloud --quiet auth configure-docker
      - name: write git-commit.txt
        run: echo "${GITHUB_SHA}" > git-commit.txt
      - name: docker build
        run: |-
          docker build \
            --build-arg GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
```
