### ISSUE TITLE
"read ETIMEDOUT" and "socket hang up" errors 

### ISSUE THREAD

**Issue by tehKapa** [google-github-actions/get-secretmanager-secrets#235]
### TL;DR

It has been about two weeks that I've been getting "read ETIMEDOUT" and "socket hang up" errors more and more frequently while loading one of the many secrets saved via Secret Manager. 

```
google-github-actions/get-secretmanager-secrets failed with: failed to access secret "projects/xxxxxxxxxxx/secrets/xxxxxxxxx/versions/latest": socket hang up
```

```
google-github-actions/get-secretmanager-secrets failed with: failed to access secret "projects/xxxxxxxxxxx/secrets/xxxxxxxxx/versions/latest": read ETIMEDOUT
```

That specific GitHub workflow has remained unchanged for at least 5 months.

### Action YAML

```yaml
deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    permissions:
      actions: write
      checks: read
      contents: read
      deployments: read
      id-token: write
      pull-requests: read
      statuses: read
    needs: [build-web, build-api]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set VPN secrets
        uses: dominicwatson/github-action-envsubst@v1
        with:
          files: .github/github.ovpn
        env:
          VPN_CA: ${{ secrets.VPN_CA}}
          VPN_CERT: ${{ secrets.VPN_CERT }}
          VPN_KEY: ${{ secrets.VPN_KEY }}
          VPN_TLS: ${{ secrets.VPN_TLS }}

      - name: Connect to VPN
        run: |-
          sudo apt-get -qq update && sudo apt-get -qq install openvpn -y
          sudo openvpn --config .github/github.ovpn --daemon

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.PAT }}
          target_url: https://xxxxxxxxxxx
          environment: xxxxxxxxxxx
          ref: master

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "xxxxxxxxxx"
          audience: "xxxxxxxx"
          service_account: "xxxxxxx@xxxxxxx.iam.gserviceaccount.com"

      - uses: "google-github-actions/get-gke-credentials@v0"
        name: Get GKE credentials
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Get secrets from GCP Secret Manager
        id: secrets
        uses: google-github-actions/get-secretmanager-secrets@v0.5.0
        with:
          secrets: |-
            REDIS_URL:projects/xxxxxxxxx/secrets/REDIS_URL
            JWT_SECRET:projects/xxxxxxxxx/secrets/JWT_SECRET
          
      - name: Set URL, secrets and config variables
        uses: dominicwatson/github-action-envsubst@v1
        with:
          files: helm/values.yaml
        env:
          REDIS_URL: ${{ steps.secrets.outputs.REDIS_URL_INTEGRATION }}
          JWT_SECRET: ${{ steps.secrets.outputs.JWT_SECRET }}
```

### Log output

```text
Run google-github-actions/get-secretmanager-secrets@v0.5.0
Error: google-github-actions/get-secretmanager-secrets failed with: failed to access secret "projects/xxxxxxxxx/secrets/xxxxxxxxx/versions/latest": socket hang up


Run google-github-actions/get-secretmanager-secrets@v0.5.0
Error: google-github-actions/get-secretmanager-secrets failed with: failed to access secret "projects/xxxxxxxxx/secrets/xxxxxxxxx/versions/latest": read ETIMEDOUT
```
