### ISSUE TITLE
use property to extra value when you store your key as json

### ISSUE THREAD

**Issue by sourceful-karlson** [google-github-actions/get-secretmanager-secrets#288]
### TL;DR

i like to have a secret written in json, so I can have multiple secret accessed by different field

### Detailed design

is it possible to have logic to access a key to that secret the way that external secret does it

**Comment by sethvargo** [comment]
> is it possible to have logic to access a key to that secret the way that external secret does it

What do you mean?

**Comment by sourceful-karlson** [comment]
The reason why I am asking is that currently there is not a way for me for mask output from a step within an expression

      - uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ inputs.projectId }}
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - id: fetch-secret
        uses: google-github-actions/get-secretmanager-secrets@v1
        with:
          secrets: |-
            secrets:projects/${{ inputs.projectId }}/secrets/${{ inputs.dbSecretName }}/versions/latest

      - id: pg-password
        name: mask the password
        run: |
          echo ${{fromJSON( steps.fetch-secret.outputs.secrets )[inputs.dbSecretPasswordField]}}
          
the echo always output the value and add-mask does not work  (https://github.com/actions/runner/issues/475)


thus can we add accessor key for me to get the right value?

**Comment by sourceful-karlson** [comment]
external secret reference refers to 

in external secret, i can store my secret in json

then i can refer the value like below

  data:
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: test-api
        version: latest
        property: POSTGRES_PASSWORD # JSON property

**Comment by sethvargo** [comment]
```yaml
  - id: fetch-secret
    uses: google-github-actions/get-secretmanager-secrets@v2
    with:
      secrets: |-
        secrets:projects/${{ inputs.projectId }}/secrets/${{ inputs.dbSecretName }}/versions/latest

  - id: pg-password
    name: mask the password
    env:
      SECRET: '${{ steps.fetch-secret.outputs.secrets }}'
    run: |
      VALUE1="$(jq .key1 <<< "${SECRET}")"
      VALUE2="$(jq .key2 <<< "${SECRET}")"
      echo "::add-mask::${VALUE1}"
      echo "::add-mask::${VALUE2}"
```

You can use `jq` or similar tools for parsing the json and extracting the values. We're not going to natively support this feature, because it then opens the door for supporting YAML and TOML and other arbitrary configuration formats stored in secrets.
