### ISSUE TITLE
Support impersonate service account

### ISSUE THREAD

**Issue by yu-iskw** [google-github-actions/get-secretmanager-secrets#310]
### TL;DR

I want to utilize impersonate service account to get a secret so that we can separate permissions to get a secret from an authenticated service account by `google-github-actions/auth`. By doing so, we can more securely manage roles and permissions for GitHub Actions.

### Detailed design

It would be good to add an optional parameter to specify an impersonate service account to the Action.

```yaml
    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v2'
      with: 
        impersonate_service_account: xxxx@xxxx.iam.gserviceaccount.com
```
